services:
  tor-guard-relay:
    build: .
    container_name: tor-guard-relay
    restart: unless-stopped
    ports:
      - "9001:9001" # ORPort
      - "9030:9030" # DirPort
      - "9050:9050" # SocksPort
    environment:
      - TOR_NICKNAME=MyTorRelay
      - CONTACT_INFO=anonymous@example.com
      - RELAY_PORT=9001
      - DIR_PORT=9030
      - RELAY_BANDWIDTH_RATE=1024
      - RELAY_BANDWIDTH_BURST=2048
      - TOR_SOCKS_PORT=9050
      - EXTERNAL_ADDRESS=your.external.ip.address
      - IPV6_EXIT=0 
      - SOCKS_POLICY=accept *:*
    volumes:
      - ./tor-data:/var/lib/tor

volumes:
  tor-data:

networks:
  default:
    driver: bridge
