version: '3'
services:
  tor-guard-relay:
    build:
      context: .
      dockerfile: Dockerfile
    image: tor-guard-relay:latest
    container_name: tor-guard-relay
    restart: unless-stopped    
    network_mode: host    
    environment:
      - TOR_NICKNAME=your_tor_nickname
      - CONTACT_INFO=your_contact_info@example.com
      - RELAY_PORT=9101
      - DIR_PORT=9030
      - RELAY_BANDWIDTH_RATE=3072
      - RELAY_BANDWIDTH_BURST=4096
      - TOR_SOCKS_PORT=127.0.0.1:9050
      - EXTERNAL_ADDRESS=your_external_ip_address
      - CONTROL_PORT=127.0.0.1:9051      
      - USE_COOKIE_AUTH=1    
    volumes:
      	- ./tor-data:/var/lib/tor    
  	user: debian-tor  
